import { CalendarDays, Mail, Search, UserRound } from "lucide-react";
import type { AppLocale } from "@/lib/i18n";

const COLUMNS = [
  { title: { es: "Por contactar", en: "Contact ready" }, card: { project: "BESS Cordillera", company: "Energía Horizonte", contact: "Andrea Rojas", owner: { es: "Equipo comercial", en: "Sales team" }, action: { es: "Enviar presentación técnica", en: "Send technical presentation" }, date: { es: "Hoy", en: "Today" }, activity: { es: "Oportunidad creada desde la ficha", en: "Opportunity created from project profile" } } },
  { title: { es: "En conversación", en: "In conversation" }, card: { project: "PFV Desierto Claro", company: "Solar Andina", contact: "Felipe Torres", owner: { es: "Patrick Bittig", en: "Patrick Bittig" }, action: { es: "Preparar reunión de ingeniería", en: "Prepare engineering meeting" }, date: { es: "06-08-2026", en: "08-06-2026" }, activity: { es: "Correo enviado al contacto", en: "Email sent to contact" } } },
  { title: { es: "Propuesta", en: "Proposal" }, card: { project: "Híbrido Altiplano", company: "Renovables del Norte", contact: "Camila Soto", owner: { es: "Equipo comercial", en: "Sales team" }, action: { es: "Actualizar alcance y precio", en: "Update scope and pricing" }, date: { es: "08-08-2026", en: "08-08-2026" }, activity: { es: "Propuesta compartida", en: "Proposal shared" } } },
  { title: { es: "Cierre", en: "Closing" }, card: { project: "BESS Pampa Sur", company: "Infraestructura Sur", contact: "Diego Silva", owner: { es: "Patrick Bittig", en: "Patrick Bittig" }, action: { es: "Confirmar orden de compra", en: "Confirm purchase order" }, date: { es: "12-08-2026", en: "08-12-2026" }, activity: { es: "Reunión comercial registrada", en: "Sales meeting logged" } } },
];

export function CrmPreview({ locale }: { locale: AppLocale }) {
  const en = locale === "en";
  return <div className="space-y-4"><div className="flex flex-wrap items-center gap-2 rounded-lg border border-neutral-200 bg-neutral-50 p-3 dark:border-neutral-800 dark:bg-neutral-900"><span className="inline-flex items-center gap-1.5 rounded-md bg-neutral-950 px-3 py-2 text-xs font-semibold text-white"><CalendarDays size={13} />Pipeline</span><div className="flex min-w-56 flex-1 items-center gap-2 rounded-md border border-neutral-200 bg-white px-3 py-2 text-xs text-neutral-400 dark:border-neutral-700 dark:bg-neutral-950"><Search size={13} />{en ? "Project, company, contact or owner..." : "Proyecto, empresa, contacto o responsable..."}</div></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{COLUMNS.map(({ title, card }) => { const localizedTitle = en ? title.en : title.es; return <section key={localizedTitle} className="rounded-lg bg-neutral-50 p-3 dark:bg-neutral-900"><div className="flex items-center justify-between"><h3 className="text-xs font-semibold text-neutral-800 dark:text-neutral-100">{localizedTitle}</h3><span className="rounded-full bg-white px-2 py-0.5 text-[10px] font-semibold dark:bg-neutral-950">1</span></div><article className="mt-3 rounded-lg border border-neutral-200 bg-white p-3 shadow-sm dark:border-neutral-800 dark:bg-neutral-950"><p className="text-[10px] font-semibold text-brand-deep">{localizedTitle.toUpperCase()}</p><p className="mt-1 text-sm font-semibold text-neutral-950 dark:text-white">{card.project}</p><p className="mt-1 text-xs text-neutral-500">{card.company}</p><div className="mt-3 space-y-2 border-t border-neutral-100 pt-3 text-[11px] dark:border-neutral-800"><p className="flex gap-1.5"><UserRound size={12} className="shrink-0 text-brand-primary" /><span><span className="font-semibold">{en ? "Contact:" : "Contacto:"}</span> {card.contact}</span></p><p className="flex gap-1.5"><UserRound size={12} className="shrink-0 text-brand-primary" /><span><span className="font-semibold">{en ? "Owner:" : "Responsable:"}</span> {en ? card.owner.en : card.owner.es}</span></p><p className="flex gap-1.5"><CalendarDays size={12} className="shrink-0 text-brand-primary" /><span><span className="font-semibold">{en ? "Next action:" : "Próxima acción:"}</span> {en ? card.action.en : card.action.es} · {en ? card.date.en : card.date.es}</span></p><p className="flex gap-1.5 text-neutral-500"><Mail size={12} className="shrink-0" />{en ? card.activity.en : card.activity.es}</p></div></article></section>; })}</div><p className="text-[11px] text-neutral-400">{en ? "Fictional pipeline representative of the Prime CRM view." : "Pipeline ficticio representativo de la vista Prime del CRM."}</p></div>;
}
